### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): TypeError: Cannot set property 'success' of undefined

### ISSUE THREAD

**Issue by SudoPlz** [BugBattle/ReactNative-SDK#19]
Another crash,

All we know is that it originates here:

https://github.com/BugBattle/ReactNative-SDK/blob/e7d15c416b5173fc5d895b043fc97e239aa29dd0/src/networklogger.ts#L80

It happened when one of our endpoints returned a 401 with the following response:
`{"status_code":401,"error":"invalid_password","message":"The user credentials were incorrect."}`

The stacktrace is obfuscated unfortunately, but there goes nothing:

```
Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot set property 'success' of undefined
TypeError: Cannot set property 'success' of undefined
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.example.client.ios:131828:51)
    at tryCallOne (/Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.example.client.ios:28464:26)
    at _callTimer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.example.client.ios:28360:17)
    at _callImmediatesPass (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.example.client.ios:28399:17)
    at callImmediates (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.example.client.ios:28609:33)
    at __callImmediates (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.example.client.ios:3062:35)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.example.client.ios:2840:34)
    at __guard (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.example.client.ios:3045:15)
    at flushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.example.client.ios:2839:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.example.client.ios:2832:33)

```

Thank you

"react-native-bugbattle-sdk": "5.0.1",
"react-native": "0.65.1",
iOS 14.5

**Comment by boehlerlukas** [comment]
Hey @SudoPlz 

Thanks again for reporting the issue. The latest update `react-native-bugbattle-sdk@5.0.2` should fix this crash. It would be great if you can verify the fix, so we can close the issue 🤗
